/**
 * Style Dictionary (v4) wiring for @mt/tokens.
 *
 * One SD build per brand×theme permutation. Custom formats emit the two
 * MT-specific artifacts (Tailwind preset + Figma importer payload); CSS/TS use
 * SD built-ins. In Phase 0 the custom formats are deliberate stubs that produce
 * valid-but-empty skeletons so the whole pipeline is proven before real token
 * values exist (Phase 1).
 */
import StyleDictionary from 'style-dictionary';
import type { Config } from 'style-dictionary/types';
import type { Permutation } from '../resolver/resolve.js';

let registered = false;

export function registerMtHooks(): void {
  if (registered) return;
  registered = true;

  // Tailwind preset — Phase 0 stub. Phase 2 maps semantic tokens → theme.extend.
  StyleDictionary.registerFormat({
    name: 'mt/tailwind-preset',
    format: async ({ dictionary, options }) => {
      const perm = (options as { mtPermutation?: string }).mtPermutation ?? '';
      return (
        `/** Generated by @mt/tokens (${perm}) — Phase 0 scaffold. Do not edit by hand. */\n` +
        `/** ${dictionary.allTokens.length} token(s) resolved. */\n` +
        `module.exports = {\n  theme: { extend: {} },\n};\n`
      );
    },
  });

  // Figma Variable importer payload — Phase 0 stub. Phase 3 maps to collections/modes.
  StyleDictionary.registerFormat({
    name: 'mt/figma-payload',
    format: async ({ dictionary, options }) => {
      const perm = (options as { mtPermutation?: string }).mtPermutation ?? '';
      const tokens = dictionary.allTokens.map((t) => ({
        path: t.path,
        type: (t as { $type?: string; type?: string }).$type ?? t.type,
        value: (t as { $value?: unknown }).$value ?? t.value,
      }));
      return JSON.stringify({ permutation: perm, version: 0, collections: [], tokens }, null, 2) + '\n';
    },
  });
}

export function makeConfig(perm: Permutation, buildDir: string): Config {
  const selector = `[data-brand="${perm.brand}"][data-theme="${perm.theme}"]`;
  return {
    tokens: perm.tokens,
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: `${buildDir}/css/`,
        options: { mtPermutation: perm.name },
        files: [
          {
            destination: `${perm.name}.css`,
            format: 'css/variables',
            options: { selector, outputReferences: true },
          },
        ],
      },
      ts: {
        transformGroup: 'js',
        buildPath: `${buildDir}/ts/`,
        options: { mtPermutation: perm.name },
        files: [{ destination: `${perm.name}.ts`, format: 'javascript/es6' }],
      },
      tailwind: {
        transformGroup: 'js',
        buildPath: `${buildDir}/tailwind/`,
        options: { mtPermutation: perm.name },
        files: [{ destination: `${perm.name}.cjs`, format: 'mt/tailwind-preset' }],
      },
      figma: {
        transformGroup: 'js',
        buildPath: `${buildDir}/figma/`,
        options: { mtPermutation: perm.name },
        files: [{ destination: `${perm.name}.json`, format: 'mt/figma-payload' }],
      },
    },
  };
}
